#!/usr/bin/with-contenv bash

if [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "**** Setting password from environment variable. ****"
else
    echo "**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****"
fi


if [ ! -d /vaults ]; then
    echo "**** Creating vaults folder. ****"
    mkdir -p /vaults;
fi

echo "********************************"
echo "**** Start Date Information ****"
echo "********************************"
echo "TZ: ${TZ}"
echo "Running dpkg-reconfigure -f noninteractive tzdata"
echo "${TZ}" >/etc/timezone
dpkg-reconfigure -f noninteractive tzdata
echo "Date UTC"
date --utc
echo "Date Local"
date
echo "Zone Info"
zdump /usr/share/zoneinfo/${TZ}
echo "Time Zone Offsets"
zdump -v /etc/localtime
echo "********************************"
echo "****  End Date Information  ****"
echo "********************************"

# export LANG=fr_BE.UTF-8
# export LANGUAGE=fr_BE.UTF-8
# export LC_ALL=fr_BE.UTF-8  *** override all other LC_*
#/usr/sbin/update-locale LANG=fr_BE.UTF-8 LANGUAGE=fr_BE.UTF-8 LC_MESSAGES=POSIX 

# Create .Xresources file if doesn't exist
if [ ! -f /config/.Xresources ]; then
   touch /config/.Xresources
   cat <<'EOF' > /config/.Xresources
XTerm*selectToClipboard: true

XTerm*renderFont: true
XTerm*faceName: MiscFixed
XTerm*faceSize: 10

XTerm*geometry: 100x30+10+10

XTerm*savelines: 20000
XTerm*rightScrollBar: true
XTerm*ScrollBar: true
XTerm*foreground: rgb:cf/cf/cf
XTerm*background: rgb:00/00/00
EOF
echo "create .Xresources"
xrdb -merge ~/.Xresources
fi

# Create .bashrc file for including TeX/texlive/bin/x86_64-linux/ in PATH for xterm non-login bash session
# Switch HOME
if [ ! -f /config/.bashrc ]; then
   touch /config/.bashrc
   cat <<'EOF' > /config/.bashrc
echo "run .bashrc"
PATH="/TeX/texlive/bin/x86_64-linux/:${PATH}"
HOME=/config
cd /vaults
EOF
fi

# permissions
chown -R abc:abc \
    /config \
    /vaults \
    /root

